const influencer = [
    {
        username: "username",
        followers: "45k followers",
        play: "139.5k",
        reach: "139.5k",
        link: "https://instagram.com/gdhyani_",
        likes: "45k",
        comments: "12k",
        engagement: "10k",
        dateUpdated: "23 June, 2023",
        type: "video",
    },
    {
        username: "username",
        followers: "45k followers",
        play: "139.5k",
        reach: "139.5k",
        link: "https://instagram.com/gdhyani_",
        likes: "45k",
        comments: "12k",
        engagement: "10k",
        dateUpdated: "23 June, 2023",
        type: "video",
    },
    {
        username: "username",
        followers: "45k followers",
        play: "139.5k",
        reach: "139.5k",
        link: "https://instagram.com/gdhyani_",
        likes: "45k",
        comments: "12k",
        engagement: "10k",
        dateUpdated: "23 June, 2023",
        type: "video",
    },
    {
        username: "username",
        followers: "45k followers",
        play: "139.5k",
        reach: "139.5k",
        link: "https://instagram.com/gdhyani_",
        likes: "45k",
        comments: "12k",
        engagement: "10k",
        dateUpdated: "23 June, 2023",
        type: "video",
    },
    {
        username: "username",
        followers: "45k followers",
        play: "139.5k",
        reach: "139.5k",
        link: "https://instagram.com/gdhyani_",
        likes: "45k",
        comments: "12k",
        engagement: "10k",
        dateUpdated: "23 June, 2023",
        type: "video",
    },
    {
        username: "username",
        followers: "45k followers",
        play: "139.5k",
        reach: "139.5k",
        link: "https://instagram.com/gdhyani_",
        likes: "45k",
        comments: "12k",
        engagement: "10k",
        dateUpdated: "23 June, 2023",
        type: "video",
    },
    {
        username: "username",
        followers: "45k followers",
        play: "139.5k",
        reach: "139.5k",
        link: "https://instagram.com/gdhyani_",
        likes: "45k",
        comments: "12k",
        engagement: "10k",
        dateUpdated: "23 June, 2023",
        type: "video",
    },
    {
        username: "username",
        followers: "45k followers",
        play: "139.5k",
        reach: "139.5k",
        link: "https://instagram.com/gdhyani_",
        likes: "45k",
        comments: "12k",
        engagement: "10k",
        dateUpdated: "23 June, 2023",
        type: "video",
    },
    {
        username: "username",
        followers: "45k followers",
        play: "139.5k",
        reach: "139.5k",
        link: "https://instagram.com/gdhyani_",
        likes: "45k",
        comments: "12k",
        engagement: "10k",
        dateUpdated: "23 June, 2023",
        type: "video",
    },
    {
        username: "username",
        followers: "45k followers",
        play: "139.5k",
        reach: "139.5k",
        link: "https://instagram.com/gdhyani_",
        likes: "45k",
        comments: "12k",
        engagement: "10k",
        dateUpdated: "23 June, 2023",
        type: "video",
    },
    {
        username: "username",
        followers: "45k followers",
        play: "139.5k",
        reach: "139.5k",
        link: "https://instagram.com/gdhyani_",
        likes: "45k",
        comments: "12k",
        engagement: "10k",
        dateUpdated: "23 June, 2023",
        type: "video",
    },
    {
        username: "username",
        followers: "45k followers",
        play: "139.5k",
        reach: "139.5k",
        link: "https://instagram.com/gdhyani_",
        likes: "45k",
        comments: "12k",
        engagement: "10k",
        dateUpdated: "23 June, 2023",
        type: "video",
    },
    {
        username: "username",
        followers: "45k followers",
        play: "139.5k",
        reach: "139.5k",
        link: "https://instagram.com/gdhyani_",
        likes: "45k",
        comments: "12k",
        engagement: "10k",
        dateUpdated: "23 June, 2023",
        type: "video",
    },
];
export default influencer;
